version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 70
      statements: 50
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - goconst
        path: (.+)_test.go
    paths:
      - .circleci
      - .github
      - scripts
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 25
  uniq-by-line: false
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - .circleci
      - .github
      - scripts
      - third_party$
      - builtin$
      - examples$
