issues:
  max-same-issues: 25
  uniq-by-line: false
  exclude-dirs:
     - .circleci
     - .github
     - scripts
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - dupl
        - goconst

run:
  timeout: 5m

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - errorlint
    - copyloopvar
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - tparallel
    - importas
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
linters-settings:
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 70
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: 50
