version: 2

release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  prerelease: auto

builds:
  - binary: anchore-k8s-inventory
    id: generic
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # Set the modified timestamp on the output binary to the git timestamp (to ensure a reproducible build)
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags: |
      -w
      -s
      -extldflags '-static'
      -X github.com/anchore/k8s-inventory/internal/version.version={{.Version}}
      -X github.com/anchore/k8s-inventory/internal/version.gitCommit={{.Commit}}
      -X github.com/anchore/k8s-inventory/internal/version.buildDate={{.Date}}
      -X github.com/anchore/k8s-inventory/internal/version.gitTreeState={{.Env.BUILD_GIT_TREE_STATE}}
  - binary: anchore-k8s-inventory
    id: fips
    env:
      - CGO_ENABLED=1
      - GOEXPERIMENT=boringcrypto
    goos:
      - linux
    goarch:
      - amd64
    # Set the modified timestamp on the output binary to the git timestamp (to ensure a reproducible build)
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags: |
      -w
      -linkmode=external
      -extldflags '-static'
      -X github.com/anchore/k8s-inventory/internal/version.version={{.Version}}
      -X github.com/anchore/k8s-inventory/internal/version.gitCommit={{.Commit}}
      -X github.com/anchore/k8s-inventory/internal/version.buildDate={{.Date}}
      -X github.com/anchore/k8s-inventory/internal/version.gitTreeState={{.Env.BUILD_GIT_TREE_STATE}}

archives:
  - id: archive-generic
    formats: [ 'tar.gz' ]
    ids:
      - generic
    name_template: 'anchore-k8s-inventory_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
  - id: archive-fips
    formats: [ 'tar.gz' ]
    ids:
      - fips
    name_template: 'anchore-k8s-inventory-fips_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers_v2:
  - id: generic
    dockerfile: Dockerfile
    ids:
      - generic
    images:
      - "anchore/k8s-inventory"
    tags:
      - "{{ .Tag }}"
      - "{{ if not .Prerelease }}v{{ .Major }}{{ end }}"
      - "{{ if not .Prerelease }}v{{ .Major }}.{{ .Minor }}{{ end }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      BUILD_DATE: "{{.Date}}"
      BUILD_VERSION: "{{.Version}}"
      VCS_REF: "{{.FullCommit}}"
      VCS_URL: "{{.GitURL}}"

  - id: fips
    dockerfile: Dockerfile
    ids:
      - fips
    images:
      - "anchore/k8s-inventory"
    tags:
      - "{{ .Tag }}-fips"
    platforms:
      - linux/amd64
    build_args:
      BUILD_DATE: "{{.Date}}"
      BUILD_VERSION: "{{.Version}}"
      VCS_REF: "{{.FullCommit}}"
      VCS_URL: "{{.GitURL}}"

