FROM gcr.io/distroless/static-debian11:debug@sha256:a0a404776dec98be120089ae42bbdfbe48c177921d856937d124d48eb8c0b951 AS build

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

WORKDIR /tmp

COPY snapshot/generic_linux_amd64_v1/anchore-k8s-inventory /

ARG BUILD_DATE
ARG BUILD_VERSION
ARG VCS_REF
ARG VCS_URL

LABEL org.opencontainers.image.created=$BUILD_DATE
LABEL org.opencontainers.image.title="anchore-k8s-inventory"
LABEL org.opencontainers.image.description="AKI (Anchore Kubernetes Inventory) can poll Kubernetes Cluster API(s) to tell Anchore which Images are currently in-use"
LABEL org.opencontainers.image.source=$VCS_URL
LABEL org.opencontainers.image.revision=$VCS_REF
LABEL org.opencontainers.image.vendor="Anchore, Inc."
LABEL org.opencontainers.image.version=$BUILD_VERSION
LABEL org.opencontainers.image.licenses="Apache-2.0"

USER 1000
HEALTHCHECK CMD ["/anchore-k8s-inventory", "version"]

ENTRYPOINT ["/anchore-k8s-inventory"]
