apiVersion: skaffold/v3
kind: Config
metadata:
  name: k8s-inventory
build:
  artifacts:
  - image: local/k8sinv
    docker:
      dockerfile: Dockerfile.skaffold
  local:
    push: false
deploy:
  helm:
    releases:
    - name: k8s-inventory-dev
      chartPath: anchore-charts/stable/k8s-inventory
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_local_k8sinv}}"
        image.tag: "{{.IMAGE_TAG}}"
      setValues:
        k8sInventory.log.level: debug
        k8sInventory.log.structured: false
        k8sInventory.quiet: false
        k8sInventory.verboseInventoryReports: true
        k8sInventory.pollingIntervalSeconds: 60
        k8sInventory.anchore.url: "http://host.docker.internal:8228"
        k8sInventory.anchore.user: "admin"
        k8sInventory.anchore.password: "foobar"
        k8sInventory.anchore.http.insecure: true
