version: 2.1

jobs:
  run-static-analysis:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/golang:<< parameters.version >>
        environment:
          GO111MODULE: "on"
          # work around for recent circle CI breaking change
          # Error: "Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38"
          DOCKER_API_VERSION: "1.38"
    # 2CPU / 4GB RAM
    resource_class: medium
    steps:

      - checkout

      - restore_cache:
          keys:
            - go-<< parameters.version >>-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}

      - run: make ci-bootstrap

      - save_cache:
          key: go-<< parameters.version >>-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}
          paths:
            - "/go/pkg/mod"
            - ".tmp"

      - run:
          name: run static analysis
          command: make static-analysis

  unit-test:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/golang:<< parameters.version >>
        environment:
          GO111MODULE: "on"
          # work around for recent circle CI breaking change
          # Error: "Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38"
          DOCKER_API_VERSION: "1.38"
    # 2CPU / 4GB RAM
    resource_class: medium
    steps:

      - checkout

      - restore_cache:
          keys:
            - go-<< parameters.version >>-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}

      - run: make ci-bootstrap

      - save_cache:
          key: go-<< parameters.version >>-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}
          paths:
            - "/go/pkg/mod"
            - ".tmp"

      - run:
          name: run unit tests
          command: make unit

  integration-test:
    parameters:
      version:
        type: string
    # Couldn't get this test to run in docker due to Circle's constraints with docker networking (not that it's impossible, just couldn't get it working)
    # This image uses go version: 1.15.7
    machine:
      image: ubuntu-1604:202101-01
    # 2CPU / 4GB RAM
    resource_class: medium
    steps:

      - checkout

      - restore_cache:
          keys:
            - go-<< parameters.version >>-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}

      - run:
          name: Bootstrap Dependencies
          command: make ci-bootstrap

      - save_cache:
          key: go-<< parameters.version >>-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}
          paths:
            - "/go/pkg/mod"
            - ".tmp"

      - run:
          name: Start Kind Cluster
          command: make cluster-up

      - run:
          name: Run Integration Tests
          command: make integration

workflows:
  "Static Analysis + Unit + Integration":
    jobs:
      - run-static-analysis:
          name: "Static Analysis"
          version: "1.15.7"
      - unit-test:
          name: "Unit Tests"
          version: "1.15.7"
      - integration-test:
          name: "Integration Tests"
          version: "1.15.7"